### PR TITLE
Create example for the RGB LED on the BW16

### PR DESCRIPTION
**Pull request by designer2k2**
## Description of Change
Example on how to Blink and Fade the RGB LED on the BW16.

It is a simple sketch showing what can be done with the RGB LED.

## Tests and Environments 
Tested on a BW16-TypeC with Arduino IDE 2.3.0 in Windows 10.

### CODE REVIEW

**Review by M-ichae-l — CHANGES_REQUESTED** [review]
Since the example is only for BW16, 
Please add the marco `BOARD_AITHINKER_BW16` to avoid compatibility problem 
`#ifdef BOARD_AITHINKER_BW16`
`#endif`

**Comment by designer2k2** [comment]
Hello @M-ichae-l ,
i added the check and it will give a error during compilation now.

But one thing, BOARD_AITHINKER_BW16 does not work for me, i have to use BOARD_RTL8720DN_BW16?

**Review by M-ichae-l — APPROVED** [review]

**Comment by M-ichae-l** [comment]
@designer2k2 
For BW16 this the related marco
https://github.com/ambiot/ambd_arduino/blob/e8df7125f9f0701eea4e57cb6fa07526cd1ced72/Arduino_package/hardware/boards.txt#L111

Refer to [early release V3.1.7](https://github.com/ambiot/ambd_arduino/releases/tag/V3.1.7-QC-V07)

**Review by M-ichae-l — CHANGES_REQUESTED** [review]
Line 12 needs to update.

**Review by M-ichae-l — APPROVED** [review]

**Pull request merged**
