### PR TITLE
Modify transfer16 API

### PR DESCRIPTION
**Pull request by s1498n089**
Modify return value of transfer16 function.

### CODE REVIEW

**Comment by S10143806H** [comment]
Dear @s1498n089, 
Thank you for your Pull Request. We have tested and tested your PR. 
Would you like to modify your code as: `_data = t.val;` |
instead of using `_data = t.msb << 8 | t.lsb;`?

The reason for the above suggestion is due to both `val`, `msb`, and `lsb` are included in the same `union` structure as shown in the code below: 
https://github.com/ambiot/ambd_arduino/blob/6bbf7b9075e94a3b0bc7fa26dcee920d7daf23e4/Arduino_package/hardware/libraries/SPI/SPI.cpp#L244
To know more about the `union` structure, please refer to this [link](https://en.cppreference.com/w/cpp/language/union).

Thank you again.

**Comment by M-ichae-l** [comment]
I believe both function `transfer` and `transfer16` return "0" for successful transfer instead of the value. So "0" is the correct return otherwise the transfer process is failed.

**Comment by s1498n089** [comment]
> Dear @s1498n089, Thank you for your Pull Request. We have tested and verified your PR. Would you like to modify your code as: **`_data = t.val;`** instead of using `_data = t.msb << 8 | t.lsb;`?
> 
> The reason for the above suggestion is due to both `val`, `msb`, and `lsb` are included in the same `union` structure as shown in the code below:
> 
> https://github.com/ambiot/ambd_arduino/blob/6bbf7b9075e94a3b0bc7fa26dcee920d7daf23e4/Arduino_package/hardware/libraries/SPI/SPI.cpp#L244
> 
> 
> To know more about the `union` structure, please refer to this [link](https://en.cppreference.com/w/cpp/language/union).
> Thank you again.

**Comment by s1498n089** [comment]
> Dear @s1498n089, Thank you for your Pull Request. We have tested and verified your PR. Would you like to modify your code as: **`_data = t.val;`** instead of using `_data = t.msb << 8 | t.lsb;`?
> 
> The reason for the above suggestion is due to both `val`, `msb`, and `lsb` are included in the same `union` structure as shown in the code below:
> 
> https://github.com/ambiot/ambd_arduino/blob/6bbf7b9075e94a3b0bc7fa26dcee920d7daf23e4/Arduino_package/hardware/libraries/SPI/SPI.cpp#L244
> 
> 
> To know more about the `union` structure, please refer to this [link](https://en.cppreference.com/w/cpp/language/union).
> Thank you again.

Dear @S10143806H 
Okay, I'll send another Pull Request after modifying the code to use union. I didn't notice it was union at the time, as I instinctively used the | operator.  Thank you for the suggestion!

**Pull request merged**
