### PR TITLE
CI by compiling all examples with github action

### PR DESCRIPTION
**Pull request by designer2k2**
-----------
## Description of Change

One way to see if the overall extension works is to check if everything compiles without error. As this is quite a task manually, github action can help to automate this!

This is a implementation of the github action "compile examples", it automatically compiles all found examples inside every library folder. 

It does this by assuming to be a BW16 and just compiles every example.  To make that work i had to change 2 examples to switch to A2 as A0 is not existing on BW16.

There are still 3 non working examples left, i dont know how to fix them:
(to reproduce the errors, just try to compile the mentioned example in the ArduinoIDE)

```
   /home/runner/work/ambd_arduino/ambd_arduino/Arduino_package/hardware/libraries/PowerSave/examples/DeepSleep_DHT_Eink_Example/DeepSleep_DHT_Eink_Example.ino:10:19: fatal error: image.h: No such file or directory
   #include "image.h"
```
```
   /home/runner/Arduino/libraries/SparkFun_ADXL313_Arduino_Library/src/SparkFunADXL313.cpp: In member function 'boolean ADXL313::beginSPI(uint8_t, SPIClass&)':
  /home/runner/Arduino/libraries/SparkFun_ADXL313_Arduino_Library/src/SparkFunADXL313.cpp:79:60: error: 'SPI_MODE3' was not declared in this scope
    _spiPort->beginTransaction(SPISettings(2000000, MSBFIRST, SPI_MODE3));
```
```
   /home/runner/work/ambd_arduino/ambd_arduino/Arduino_package/hardware/libraries/WiFi/examples/WiFiControlCar/WiFiControlCar.ino:16:20: fatal error: Car2wd.h: No such file or directory
   #include "Car2wd.h"
```

Please feel free to modify this PR to fix the errors.

## Tests and Environments 
Testrun on github: https://github.com/designer2k2/ambd_arduino/actions/runs/7964058283/job/21740849932

### CODE REVIEW

**Comment by M-ichae-l** [comment]
@designer2k2 
Thank you! This workflow is really helps! 
I will review it as soon as possible. Sorry for the delay.

**Comment by designer2k2** [comment]
thanks to @Kyderio  fix the SPI issue with #222 

Now there are only 2 failing examples left, both are missing a file:

```
   /home/runner/work/ambd_arduino/ambd_arduino/Arduino_package/hardware/libraries/PowerSave/examples/DeepSleep_DHT_Eink_Example/DeepSleep_DHT_Eink_Example.ino:10:19: fatal error: image.h: No such file or directory
   #include "image.h"
```

```
   /home/runner/work/ambd_arduino/ambd_arduino/Arduino_package/hardware/libraries/WiFi/examples/WiFiControlCar/WiFiControlCar.ino:16:20: fatal error: Car2wd.h: No such file or directory
   #include "Car2wd.h"
```

**Comment by designer2k2** [comment]
found the problem, it needed 2 librarys:  AmebaEink and AmebaMotors   so they are now added.

But this example does still not work: Arduino_package/hardware/libraries/WiFi/examples/**WiFiControlCar**

It now fails with many errors:

```
   /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp: In function 'void carTask(const void*)':
  /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp:32:43: error: 'os_signal_wait' was not declared in this scope
           evt = os_signal_wait(0, 0xFFFFFFFF);
                                             ^
  /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp:111:63: error: 'os_signal_set' was not declared in this scope
                       os_signal_set(pCar->tid, evt.value.signals);
                                                                 ^
  /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp:119:63: error: 'os_signal_set' was not declared in this scope
                       os_signal_set(pCar->tid, evt.value.signals);
                                                                 ^
  /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp: In member function 'void Car2wd::begin()':
  /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp:168:69: error: 'os_thread_create' was not declared in this scope
       tid = os_thread_create(carTask, this, OS_PRIORITY_REALTIME, 1024);
                                                                       ^
  /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp: In member function 'void Car2wd::end()':
  /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp:172:28: error: 'os_thread_terminate' was not declared in this scope
       os_thread_terminate(tid);
                              ^
  /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp: In member function 'void Car2wd::setAction(unsigned char, unsigned char)':
  /home/runner/Arduino/libraries/AmebaMotors/Car2wd.cpp:189:31: error: 'os_signal_set' was not declared in this scope
           os_signal_set(tid, sig);
                                 ^
```

this also happens when you run the example inside the Arduino IDE

**Comment by M-ichae-l** [comment]
@designer2k2 
Thanks again！
This example is highly customized and needs more modification.  
I have some suggestions of current statues. 
- for "WiFiControlCar", can we edit yml files to avoid compiling this example 
    - also can use for future uniquely examples that needs to be avoided. 
- for "fqbn: realtek:AmebaD:Ai-Thinker_BW16"
    - looks like all this test is only for BW16, if we want to achieve all types of boards. Do we need to do multiple `Compile examples`, each boards runs 1 time under 'steps'

**Comment by designer2k2** [comment]
Hello @M-ichae-l ,
i expanded the boards and filled in a example list. It now fails here:

[Ameba_AMB23](https://github.com/ambiot/ambd_arduino/actions/runs/8162329466/job/22313078806?pr=221#logs)
- the IR examples.  I assume this is correct as the overview page does not mention IR? https://www.amebaiot.com/en/amebad-mini-arduino-getting-started/

[u-blox_NORA-W30](https://github.com/ambiot/ambd_arduino/actions/runs/8162329466/job/22313079880?pr=221#logs)
- IR fail, but here its missing IR_RX, IR_TX pin macro, as the datasheet mentions IR? [Datasheet Page 16](https://content.u-blox.com/sites/default/files/documents/NORA-W30_DataSheet_UBX-22021117.pdf)
- SPI Bus 1 missing? many failed examples with SPI1_MOSI, SPI1_MISO, SPI1_SCLK, SPI1_SS not found

Any guidance on how to address this errors?

**Comment by M-ichae-l** [comment]
There many check errors due to `dev_ci_compile_examples` name is different. Let us merge and review the result.

**Comment by M-ichae-l** [comment]
[All Pass](https://github.com/ambiot/ambd_arduino/actions/runs/8186699822)
@designer2k2 
Great efforts! Many thanks for the contributions.

**Comment by designer2k2** [comment]
awesome 💯

**Pull request merged**
