### PR TITLE
Update OTA Porting for AmebaD Arduino SDK

### PR DESCRIPTION
**Pull request by S10143806H**
- Add the OTA Server tool: `DownloadServer.exe`
- Update `platform.txt` where the OTA Server tool can be hosted on the Arduino network port
- Add the OTA examples and source files
- Update `ard_socket.c` and `ard_socket.h`: add in APIs for OTA socket connection
- Update `arduino.a` to avoid "Cannot allocate pbuf to receive packet" warning message keeps appearing

### CODE REVIEW

**Comment by jdt1** [comment]
Would you mind to explain how to use this? 

I have flashed the OTA_Basic sketch on my AMB23 board, I can discover it using mDNS. But when I run the DownloadServer, it simply says "Waiting for client...". It seems like the DownloadServer assumes that the ameba board will contact it, whereas the ameba board is waiting for something to push a binary to it. Is that correct, or is there something else wrong?

Is there a different tool that actually pushes code to the device, or is there example code that will contact the server to request a new binary?

**Comment by M-ichae-l** [comment]
@S10143806H  could you please resolve the issue. Then we can processed to merge.

**Comment by jdt1** [comment]
If someone is reading this, I managed to make OTA updates work by adapting this slightly:
https://github.com/MXV3A/BW16-OTA-Updates

I only modified the library.properties file to work for _AmebaD_ (which includes RTL8722DM / AMB23, which I am using) instead of _ameba_. Using the (at the moment) latest ambd_arduino release, you will need to replace `os_thread_create` with `os_thread_create_arduino` for the non-blocking variants.

If you're using RTL8722DM, this should work:
https://github.com/jdt1/AMB23-OTA-Updates

**Comment by S10143806H** [comment]
> I managed to make OTA updates work by adapting this slightly: https://github.com/MXV3A/BW16-OTA-Updates
> 
> Perhaps most importantly, this includes _UploadServer.exe_ that pushes firmware to a device, which I was missing.
> 
> I only modified the library.properties file to work for _AmebaD_ (which includes RTL8722DM / A

Hi @jdt1 ,

Thanks for your contribution.

I will upload the `DownloadServer` executable file that works on 3OS to the dev branch of this repository soon. 

I will download and play with your OTA update once my PR is done.

**Comment by S10143806H** [comment]
> I managed to make OTA updates work by adapting this slightly: https://github.com/MXV3A/BW16-OTA-Updates
> 
> Perhaps most importantly, this includes _UploadServer.exe_ that pushes firmware to a device, which I was missing.
> 
> I only modified the library.properties file to work for _AmebaD_ (which includes RTL8722DM / A

Hi @jdt1 ,

Thanks for your contribution.

I will upload the `DownloadServer` executable file that works on 3OS to the dev branch of this repository soon. 

I will download and play with your OTA update

**Pull request closed without merging**
